### PR TITLE
Fix regression on Windows; run sanity tests on Windows

### LINKED ISSUE #161: [BUG]: Unable to use kube-linter in windows
**System info:**
 - Windows

**Describe the bug**
C:\XXX\Kube-Linter>kube-linter lint kube-test1.yaml
**Error: UNEXPECTED: failed to load built-in checks: loading file dangling-service.yaml: open yamls\dangling-service.yaml: file does not exist**

**To Reproduce**
Installed kube-linter in windows and it failed with the above issue

### PR DESCRIPTION
**Pull request by viswajithiii**
Fixes #161

### CODE REVIEW

**Review by RTann — APPROVED** [review]

File: pkg/builtinchecks/built_in_checks.go [hunk 1]
```diff
@@ -47,7 +48,9 @@ func List() ([]config.Check, error) {
 				loadErr = errors.Errorf("found unexpected entry %s in yamls directory", entry.Name())
 				return
 			}
-			contents, err := yamlFiles.ReadFile(filepath.Join("yamls", entry.Name()))
+			// Do NOT use filepath.Join here, because embed always uses `/` as the separator,
+			// irrespective of the OS we're running.
+			contents, err := yamlFiles.ReadFile(fmt.Sprintf("yamls/%s", entry.Name()))
```
Comment (misberner) [inline pkg/builtinchecks/built_in_checks.go:53]: Too late, but I think it would have been better to simply use `path.Join` here rather than `fmt.Sprintf`
